#!/bin/bash

kubectl() {
    local clusters=(cluster-small cluster-medium cluster-big)
    if [ "${1}" == "config" ] && [ "${2}" == "use-context" ] && [[ "${clusters[*]}" =~ $3 ]]; then
        KUBECTL_CONTEXT="${3}"
        echo "setting context to ${3}"
    fi

    if [ "${1}" == "config" ] && [ "${2}" == "current-context" ]; then
        echo "${KUBECTL_CONTEXT}"
    fi

    if [ "${1}" == "get" ] && [ "${2}" == "nodes" ] && [ "${3}" == "-o=jsonpath={range .items[*]}{.status.allocatable.cpu}{'\t'}{.status.allocatable.memory}{'\n'}{end}" ]; then

        if [ "${KUBECTL_CONTEXT}" == "cluster-small" ]; then 
            echo "449m	1351126Ki"
            echo "449m	1351126Ki"
        fi


        if [ "${KUBECTL_CONTEXT}" == "cluster-medium" ]; then 
            echo "940m	2702252Ki"
            echo "940m	2702252Ki"
            echo "4      15850212Ki"
            echo "8      31700424Ki"
            echo "8      31700424Ki"
            echo "8      31700424Ki"
        fi

        if [ "${KUBECTL_CONTEXT}" == "cluster-big" ]; then 
            echo "940m	  2702252Ki"
            echo "940m	  2702252Ki"
            echo "4      15850212Ki"
            echo "4      15850212Ki"
            echo "8      31700424Ki"
            echo "8      31700424Ki"
            echo "16     63400848Ki"
            echo "16     63400848Ki"
            echo "16     63400848Ki"
            echo "16     63400848Ki"
            echo "16     63400848Ki"
            echo "16     63400848Ki"
            echo "16     63400848Ki"
            echo "16     63400848Ki"
            echo "16     63400848Ki"
            echo "16     63400848Ki"
            echo "16     63400848Ki"
            echo "16     63400848Ki"
            echo "16     63400848Ki"
            echo "16     63400848Ki"
            echo "16     63400848Ki"
            echo "16     63400848Ki"
            echo "16     63400848Ki"
            echo "16     63400848Ki"
            echo "16     63400848Ki"
            echo "16     63400848Ki"
            echo "32     63400848Ki"
            echo "32     63400848Ki"
            echo "32     63400848Ki"
            echo "32     63400848Ki"
            echo "32     63400848Ki"
            echo "32     63400848Ki"
        fi

    fi


    # Get pod requests
    if [ "${1}" == "get" ] && [ "${2}" == "pod" ] && [ "${3}" == "--all-namespaces" ] && [ "${4}" == "-o=jsonpath={range .items[*]}{range .spec.containers[*]}{.resources.requests.cpu}{'\t'}{.resources.requests.memory}{'\n'}{end}{'\n'}{end}" ]; then

        if [ "${KUBECTL_CONTEXT}" == "cluster-small" ]; then 
            echo "10m"
            echo ""
            echo "50m   300Mi"
            echo "5m    32Mi"
            echo "5m    32Mi"
        fi

        if [ "${KUBECTL_CONTEXT}" == "cluster-medium" ]; then 
            echo "10m"
            echo "10m"
            echo "10m"
            echo ""
            echo ""
            echo "10m"
            echo "50m   300Mi"
            echo "100m  70Mi"
            echo "100m"
            echo "5m    32Mi"
            echo "2    1G"
            echo "2    1G"
            echo "2    1G"
            echo "2    1G"
            echo "3    2G"
            echo "3    2G"
            echo "3    2G"
            echo "3    2G"
            echo "5m    32Mi"
            echo "500m  256Mi"
            echo "500m  256Mi"
        fi

        if [ "${KUBECTL_CONTEXT}" == "cluster-big" ]; then 
            echo "10m"
            echo "10m"
            echo ""
            echo "10m"
            echo "50m   300Mi"
            echo "100m  70Mi"
            echo "100m"
            echo "5m    32Mi"
            echo "2    1G"
            echo "5m    32Mi"
            echo "500m  256Mi"
            echo "500m  256Mi"
            echo ""
            echo "2    1G"
            echo "2    1G"
            echo "2    3G"
            echo "2    3G"
            echo "2    4G"
            echo "2    4G"
            echo "3    5G"
            echo "3    5G"
            echo "3    7G"
            echo "3    7G"
            echo "2    8G"
            echo "2    8G"
            echo "2    8G"
            echo "2    8G"
            echo "2    8G"
            echo "2    8G"
            echo "4    5G"
            echo "4    5G"
            echo "4    5G"
            echo "4    5G"
            echo "4    5G"
            echo "4    5G"
            echo "6    4G"
            echo "6    4G"
            echo "6    4G"
            echo "6    4G"
            echo "6    4G"
            echo "6    4G"
        fi




    fi

}
